services:
  # 1. GMU Social Backend (Node.js)
  - type: web
    name: gmu-social-api
    env: node
    rootDir: server
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false

  # 2. GMU React Frontend
  - type: web
    name: gmu-frontend
    env: static
    rootDir: client
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: gmu-social-api
          type: web
          property: host
